# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codeperf < Formula
  desc "Export, persist and compare profiling data using https://codeperf.io."
  homepage "https://codeperf.io"
  version "0.0.20"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codeperfio/codeperf/releases/download/v0.0.20/codeperf_darwin_amd64.tar.gz"
      sha256 "eb15fa9da6b603f4ebb08dd155ef927f82f973e6d99e2726c0be9b89b778ad0a"

      def install
        bin.install "codeperf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codeperfio/codeperf/releases/download/v0.0.20/codeperf_darwin_arm64.tar.gz"
      sha256 "4a553705e7bbaba6004f67aeb2b95b70f80ac9b6ff3c0ffa848d31f0bf2eaa5e"

      def install
        bin.install "codeperf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/codeperfio/codeperf/releases/download/v0.0.20/codeperf_linux_amd64.tar.gz"
      sha256 "f91d6b9a3d37dc545d20ff4a48320d58923b45a3ba1bc31f1941b7fd9a1c3a42"

      def install
        bin.install "codeperf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codeperfio/codeperf/releases/download/v0.0.20/codeperf_linux_arm64.tar.gz"
      sha256 "88e48162d78a5c03ce379661a5407fa0cdb9c3b186f009d79f2f46a1194f126c"

      def install
        bin.install "codeperf"
      end
    end
  end
end
